before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true

language: node_js

node_js:
  - "6"
  - "8"
  - "9"
  - "10"

script:
  - yarn run lint
  - yarn run test

sudo: required
